# SPDX-FileCopyrightText: 2024 Thiago Masato Costa Sueto <thiago.sueto@kde.org>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "breeze-icons"
SPDX-PackageSupplier = "none"
SPDX-PackageDownloadLocation = "https://invent.kde.org/frameworks/breeze-icons"

[[annotations]]
path = "**.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL"
